# ZKP Verifier Generation Script
# Run with: npm run circuits:verifier

Write-Host "=== Generating Solidity Verifier ===" -ForegroundColor Cyan
Write-Host ""

# 1. Robust Path Resolution (Works from ANY folder)
$ScriptPath = $MyInvocation.MyCommand.Path
$ScriptDir = Split-Path $ScriptPath
$CircuitDir = Join-Path $ScriptDir ".."
$BuildDir = Join-Path $CircuitDir "build"
$VoteBuildDir = Join-Path $BuildDir "vote"

# Define Paths
# IMPORTANT: Matches the name generated by setup.ps1
$ZKeyFinal = Join-Path $VoteBuildDir "vote_final.zkey" 

# Target: packages/dao_voting/contracts/core/VoteVerifier.sol
$ContractsDir = Join-Path $ScriptDir "../../contracts/core"
$VerifierPath = Join-Path $ContractsDir "VoteVerifier.sol"

# 2. Check Prerequisites
if (!(Test-Path $ZKeyFinal)) {
    Write-Host "❌ Error: vote_final.zkey not found." -ForegroundColor Red
    Write-Host "   Looked at: $ZKeyFinal" -ForegroundColor Gray
    Write-Host "   Run 'npm run circuits:setup' first." -ForegroundColor Yellow
    exit 1
}

# Ensure contracts directory exists
if (!(Test-Path $ContractsDir)) {
    New-Item -ItemType Directory -Path $ContractsDir | Out-Null
}

# 3. Generate Verifier
Write-Host "Generating VoteVerifier.sol..." -ForegroundColor Yellow
Write-Host "   Source: $ZKeyFinal" -ForegroundColor Gray
Write-Host "   Target: $VerifierPath" -ForegroundColor Gray

# Use npx snarkjs to generate the code
cmd /c npx snarkjs zkey export solidityverifier "$ZKeyFinal" "$VerifierPath"

# 4. Patch Solidity Version (Optional but recommended)
if (Test-Path $VerifierPath) {
    $Content = Get-Content $VerifierPath
    # Change specific pragma to a range that includes 0.8.x
    $Content = $Content -replace "pragma solidity \^0.6.11;", "pragma solidity ^0.8.0;"
    # Add License Identifier if missing
    if (!($Content -match "SPDX-License-Identifier")) {
        $Content = "// SPDX-License-Identifier: MIT`n" + $Content
    }
    # Rename contract to avoid conflicts
    $Content = $Content -replace "contract Verifier", "contract VoteVerifier"
    
    $Content | Set-Content $VerifierPath
    
    Write-Host "✅ Verifier generated and patched successfully!" -ForegroundColor Green
} else {
    Write-Host "❌ Verifier generation failed." -ForegroundColor Red
    exit 1
}